- name: Create local directory to work from
  file: path={{ scheduled_pull['working_directory'] }} state=directory owner=root group=root mode=0751

- name: Create crontab entry to clone/pull git repository
  ansible.builtin.cron:
    name: "ansible-pull"
    hour: "*/8"
    job: "ansible-pull -d {{ scheduled_pull['working_directory'] }} -U {{ scheduled_pull['repo_url'] }} >>{{ scheduled_pull['logfile'] }} 2>&1"
    state: present

- name: Create logrotate entry for ansible-pull.log
  template: src=templates/etc_logrotate.d_ansible-pull.j2 dest=/etc/logrotate.d/ansible-pull owner=root group=root mode=0644